// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramsManager.DAL.Database;

#nullable disable

namespace ProgramsManager.DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramsManager.DAL.Database.DBModels.Plate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Offer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Plate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e938b5f2-490e-4530-9e9d-a90c07d66040"),
                            DateActivity = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blue 20",
                            Offer = true
                        },
                        new
                        {
                            Id = new Guid("4ef9acef-8e8a-41cf-8458-dda3fae62fb0"),
                            DateActivity = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orange 20",
                            Offer = false
                        },
                        new
                        {
                            Id = new Guid("1963818c-3edb-4b6a-b561-a53a827f5b53"),
                            DateActivity = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Black 20",
                            Offer = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
